### ISSUE TITLE
19 -- Todo App: There and Back Again -- Randall Lee

### ISSUE THREAD

**Issue by rclee** [TheIronYard--Orlando/iOS--2015--SPRING#77]
# Homework 19

## In Due Time - Part 2
Using the first version of In Due Time, add the following functionality:

* Add an info button to each todo item cell to allow the user to enter the _todo details_ screen.
* Create a _todo details_ screen that provides cells for:
	*  the name or description of the todo item
	* a place to mark the item as complete or not complete
	* a date field to set a due date
	* a location field that shows a map and allows the user to search for nearby POIs (MKLocalSearch)
	* a notes field that allows the user to add notes to the todo item (UITextView)
	* A button to delete the todo item (also could be in the navbar)

#### Storyboard Tasks

* [x] Add an accessory detail button
* [x] push detail view onto detail button in cell
* [x] create a detail table view(TodoDetailTableViewController)
* [x] -static cells

* [x] - 1st cell - text field - title w/ completed button

* [x] - 2nd cell - due date w/ label "tap to set"

* [x] - create (DueDatePickerViewController) modal view to date picker - cancel and done button

* [x] - 3rd cell - location label w/ search field(text field)  - tap on text field to  initiate search - request access to GPS - clear cell or change color/placeholder text if search fails

* [x] - 4th cell - Notes label w/ text view filling in the rest of the field - larger cell 100 - 

* [ ] - 5th cell delete cell to delete - confirm or delete (UIAlertview)

* [ ] --modal table view POIResultsTableViewController - list of names and addresses   - cleanup cell if cancel is pressed  - prototype cells

#### Code Tasks

* [ ]  push info from cell to detail screen
* [x] create classes for views and custom classes in storyboard
* [x] - IBOutlets to static cells
* [ ] - in the POIResultsTVC select an address, clear text field, and show address or title in location cell
* [ ] - prompt text "please select an address for location"

* [ ] - logic in viewdidload for detail segue
* [ ] - add to model object - NSDate for datepicker/NSString for location/NSString for Notes
* [ ] - pass duedate to date selector if one exists - destinationviewcontroller
